<a href="https://colab.research.google.com/github/MatiasO2312/Aprendizaje-Automatico/blob/main/Clase%201/Clase%201%20-%20AA%20-%20Matias%20Oroz%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


print("Ejercicios de Arrays y Matrices con NumPy - Semana 1")

# Ej1: Array de 10 ceros
ej1 = np.zeros(10)
print("\nEj1:", ej1)

# Ej2: Números 1 al 20
ej2 = np.arange(1, 21)
print("\nEj2:", ej2)

# Ej3: Números pares 2 al 50
ej3 = np.arange(2, 51, 2)
print("\nEj3:", ej3)

# Ej5: Matriz 4x4 aleatoria 0-1
ej5 = np.random.rand(4, 4)
print("\nEj5:\n", ej5)

# Ej6: Suma elemento a elemento
a = np.array([1,2,3])
b = np.array([4,5,6])
ej6 = a + b
print("\nEj6:", ej6)

# Ej7: Multiplicación de matrices 3x3
mat7_1 = np.random.randint(1, 11, (3,3))
mat7_2 = np.random.randint(1, 11, (3,3))
ej7 = np.dot(mat7_1, mat7_2)
print("\nEj7 - Mat1:\n", mat7_1)
print("Mat2:\n", mat7_2)
print("Producto:\n", ej7)

# Ej8: Array 15 valores aleatorios 1-100, max/min/promedio
ej8 = np.random.randint(1, 101, 15)
print("\nEj8:", ej8)
print("Max:", np.max(ej8), "Min:", np.min(ej8), "Promedio:", np.mean(ej8))

# Ej9: Matriz 5x5 (1-25), extraer diagonal
ej9 = np.arange(1, 26).reshape(5,5)
diag9 = np.diag(ej9)
print("\nEj9 - Matriz:\n", ej9)
print("Diagonal:", diag9)

# Ej10: Matriz 5x5 aleatoria 1-20, suma filas/columnas
ej10 = np.random.randint(1, 21, (5,5))
print("\nEj10 - Matriz:\n", ej10)
print("Suma filas:", np.sum(ej10, axis=1))
print("Suma columnas:", np.sum(ej10, axis=0))

Ejercicios de Arrays y Matrices con NumPy - Semana 1

Ej1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Ej2: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Ej3: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]

Ej5:
 [[0.82873751 0.35675333 0.28093451 0.54269608]
 [0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143]
 [0.70685734 0.72900717 0.77127035 0.07404465]]

Ej6: [5 7 9]

Ej7 - Mat1:
 [[ 7 10  9]
 [ 7  9  8]
 [ 2  1  7]]
Mat2:
 [[7 8 5]
 [3 8 6]
 [3 1 3]]
Producto:
 [[106 145 122]
 [100 136 113]
 [ 38  31  37]]

Ej8: [47 78  3  1  5 90 14 27  9 79 15 90 42 77 51]
Max: 90 Min: 1 Promedio: 41.86666666666667

Ej9 - Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]

Ej10 - Matriz:
 [[ 7 17 20  4  5]
 [ 7 13 15 11  4]
 [13  7 19  2 10]
 [13  6 12 12 20]
 [11  7  1  1 20]]
Suma filas: [53 50 51 63 40]
Suma columnas: [51 50 67 30 59]
